"""auto create firms, users & votes tables

Revision ID: 04a24b602c66
Revises: 
Create Date: 2025-04-22 08:07:34.766501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a24b602c66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('firms', sa.Column('licenced', sa.Boolean(), server_default='TRUE', nullable=False))
    # op.add_column('firms', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(func.now())'), nullable=False))
    # op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(func.now())'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'created_at')
    # op.drop_column('firms', 'created_at')
    # op.drop_column('firms', 'licenced')
    # ### end Alembic commands ###
